# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI - Build + Lint + Test

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: '9.1.1'

            - name: Use Node.js '20'
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'pnpm'

            - name: 📦 Install dependencies
              run: pnpm install

            - name: 🔍 Run Build
              run: pnpm build

            - name: 🎨 Run Lint
              run: pnpm lint

            - name: 🧪 test the build
              run: pnpm test
