name: Github + NPM Release

on:
    push:
        branches:
            - 'main'

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v4
              id: release
              with:
                  target-branch: main

            - uses: actions/checkout@v3
              if: ${{ steps.release.outputs.release_created }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              if: ${{ steps.release.outputs.release_created }}
              with:
                  version: '9.1.1'

            - name: Use Node.js '20'
              uses: actions/setup-node@v4
              if: ${{ steps.release.outputs.release_created }}
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@lukso'
                  cache: 'pnpm'

            - name: 📦 Install dependencies
              if: ${{ steps.release.outputs.release_created }}
              run: pnpm install --frozen-lockfile

            - name: 🔍 Run Build
              if: ${{ steps.release.outputs.release_created }}
              run: pnpm build

            - name: 📢 Publish on NPM
              if: ${{ steps.release.outputs.release_created }}
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
